### ISSUE TITLE
通过umi build，build 之后不能访问

### ISSUE THREAD

**Issue by linchanglin** [ant-motion/landing-umi-example#2]

**Comment by jljsj33** [comment]
访问什么？？？build 之后直接用 site 里的文件就行了。。。。

**Comment by jljsj33** [comment]
`npm start`

**Comment by linchanglin** [comment]
我umi build 之后生成了  dist 目录 里面三个文件 index.html  umi.js  umi.css .  我本地起的http 服务  访问index.html 就报错了，报错信息如下。
_http_outgoing.js:722
      throw new ERR_INVALID_ARG_TYPE('chunk', ['string', 'Buffer'], chunk);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at ServerResponse.end (_http_outgoing.js:722:13)
    at /Users/cengchanglin/learning-project/react/umiexample/http.js:29:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:392:12)

**Comment by jljsj33** [comment]
这啥子东西啊？？？你http 服务是啥启的？？

**Comment by jljsj33** [comment]
本地测了没啥问题。。。。
`npm start`
![image](https://user-images.githubusercontent.com/6802825/54903958-203a1e80-4f18-11e9-818f-a2ea0c6dd03e.png)

`npm build` 的文件
![image](https://user-images.githubusercontent.com/6802825/54903968-26c89600-4f18-11e9-971b-e32bfa24284d.png)

**Comment by jljsj33** [comment]
后面不要加 index.html,, 是 127.0.0.1,, 不是 127.0.0.1/index.html

**Comment by linchanglin** [comment]
你这个怎么没有端口啊，我就是在起的本地node 服务器。我把build 的包放在远程服务器上也不行。你的这个项目没有可以build 的 git 地址 我去看看，谢谢啦

**Comment by linchanglin** [comment]
请问下你的 .umirc.js是怎么配置的啊

**Comment by jljsj33** [comment]
https://ant-motion.github.io/landing-umi-example/

.umirc.js 里加 

```
export default {
  exportStatic: {
    htmlSuffix: true,
    dynamicRoot: true,
  },
}
```

**Comment by jljsj33** [comment]
https://github.com/ant-motion/landing-umi-example/commit/51408fdd9483ca586f16ae9394504b001f8ad951

**Comment by jljsj33** [comment]
https://umijs.org/zh/guide/deploy.html#html-%E5%90%8E%E7%BC%80
