### ISSUE TITLE
umi: command not found

### ISSUE THREAD

**Issue by kehuo** [ant-motion/landing-umi-example#3]
在 router 分支下， package.json 好像忘记添加 umi 依赖了.

**Comment by kehuo** [comment]
在git clone 并  npm install 后报错 umi: command not found.
查看 package.json 后发现好像demo中忘记添加 umi 依赖了.

**Comment by jljsj33** [comment]
`yarn global add umi ` or `npm install -g umi` umi 是全局的，，https://umijs.org/
